
sudo: required

notifications:
  email: false

language: php

dist: xenial

services:
    - mysql

php:
    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
    - 7.2

env:
  global:
    - PLUGINDIR=blocks/mytest

matrix:
    # Enable fast finish.
    # This will fail the build if a single job fails (except those in allow_failures).
    # It will not stop the jobs from running.
    fast_finish: true

cache:
    directories:
      - $HOME/.composer/cache
      - $HOME/.npm

install:
  - |
    if [ -n "$GITHUB_APITOKEN" ]; then
      composer config github-oauth.github.com $GITHUB_APITOKEN;
      echo 'auth.json' >> .git/info/exclude
    fi

    # Install composer
    travis_retry composer install --prefer-dist --no-interaction;

before_script:
  - |
    phpenv config-rm xdebug.ini
    mkdir -p "$HOME"/roots/phpunit
    cp config-dist.php config.php

    # Travis data source info
    sed -i \
      -e "s%= 'moodle'%= 'travis_ci_test'%" \
      -e "s%= 'password'%= ''%" \
      config.php;
    sed -i \
      -e "s%= 'pgsql'%= 'mysqli'%" \
      -e "s%= 'username'%= 'travis'%" \
      -e "s%=> 'utf8mb4_unicode_ci'%=> 'utf8mb4_bin'%" \
      config.php;

    # The wwwroot and dataroot.
    sed -i \
      -e "s%http://example.com/moodle%https://localhost%" \
      -e "s%/home/example/moodledata%/home/travis/roots/base%" \
      config.php;

    # PHPUnit config info
    sed -i \
      -e "/require_once/i \\\$CFG->phpunit_dataroot = '\/home\/travis\/roots\/phpunit';" \
      -e "/require_once/i \\\$CFG->phpunit_prefix = 'p_';" \
      config.php;

script:
  - |
    # Exit code 1 - Plugin directory was not defined
    if [ -z "$PLUGINDIR" ]; then
      printf "PLUGINDIR must be define in environment!"
      exit 1
    elsif [ -d "$PLUGINDIR" ]; then
      printf "Cannot find plugin... Please check PLUGINDIR environment variable"
      exit 2
    fi

    # Run PHP unit test
    vendor/bin/phpunit --fail-on-risky --disallow-test-output --verbose "{$PLUGINDIR}/tests";

after_success:
  - |
    printf "Unit testing was successful\n"

#  - git checkout passed
#  - git pull
#  - git merge $TRAVIS_BRANCH
#  - git push origin passed
#  - git config --global user.email "smo@praxis.dk"
#  - git config --global user.name "Sam Møller"
#  - git remote add origin https://${GITTOKEN}@github.com/sampraxis/moodle.git > /dev/null 2>&1
#  - git pull origin passed